### PR TITLE
Add 2018/System.IO.Enumerations/

### PR DESCRIPTION
**Pull request by terrajobst**
@JeremyKuhne please take a look to make sure I captured everything correctly.

### CODE REVIEW

**Comment by cdmihai** [comment]
My feedback:
- required for CPS and benefit for MSBuild: BeginDirectoryEnumeration / EndDirectoryEnumeration callbacks.
- benefit for MSBuild: enumeration overload accepting a RecurseDirectory callback that also returns the new state object to use for that subtree (either this or we'll have to use a global dictionary in the global state object to keep the state per subtree).

**Comment by terrajobst** [comment]
@cdmihai 

Thanks, added to the notes

**Comment by ahsonkhan** [comment]
> required for CPS and benefit for MSBuild

What is CPS?

**Comment by JeremyKuhne** [comment]
> What is CPS?

Common Project System. One of the components of VS.

**Pull request merged**
