### PR TITLE
WIP: Add .NET Core 2.0 vs. .NET Core 2.1

### PR DESCRIPTION
**Pull request by terrajobst**
@KrzysztofCwalina @joshfree @ahsonkhan

This isn't ready yet -- as discussed in the meeting I'll add summarize and assign the area owners.

### CODE REVIEW

**Comment by terrajobst** [comment]
> +    public static class AssertExtensions {

We should probably remove whatever test library brings this in.


---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:24 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        bool System.IEquatable<System.IntPtr>.Equals(IntPtr value);

Why did we change it?

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:194 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static ReadOnlySpan<T> AsReadOnlySpan<T>(this ArraySegment<T> arraySegment);

should be segment

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:244 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +    public static class PlatformDetection {

Should we look at this for RuntimeInformation?

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:324 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static implicit operator ReadOnlyMemory<T> (ArraySegment<T> arraySegment);

segment

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:413 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public bool Equals(SequencePosition position);

other

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:461 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static implicit operator Span<T> (ArraySegment<T> arraySegment);

segment

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:501 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        bool System.IEquatable<System.UIntPtr>.Equals(UIntPtr value);

other

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:581 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static void CopyTo<T>(this ref ReadOnlySequence<T> sequence, Span<T> destination);

source

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:625 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static void Write<T>(this IBufferWriter<T> bufferWriter, ReadOnlySpan<T> source);

writer

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:628 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static void Write<T>(this IBufferWriter<T> bufferWriter, ReadOnlySpan<T> source);

value

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:628 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +    public interface IRetainable {

This is the new System.Diagnostics.Process. :-)

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:635 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
>  namespace System.Buffers {

Should we revisit the contents of this namespace? It seems we have a bunch of types that are plumbing that should be in a nested namespace, such as IRetainable.

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:623 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        protected internal abstract bool TryGetArray(out ArraySegment<T> arraySegment);

segment

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:672 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +    public delegate void ReadOnlySpanAction<T, in TArg>(ReadOnlySpan<T> span, TArg arg); {

Looks like plumbing. Should be in sub namespace.

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:716 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +    public delegate void SpanAction<T, in TArg>(Span<T> span, TArg arg); {

Looks like plumbing. Should be in sub namespace.

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:722 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static short ReadInt16BigEndian(ReadOnlySpan<byte> buffer);

source

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:750 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryWriteInt16BigEndian(Span<byte> buffer, short value);

destination

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:784 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public virtual void Write(ReadOnlySpan<char> chars);

buffer

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:10560 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static Memory<T> AsMemory<T>(ReadOnlyMemory<T> readOnlyMemory);

memory

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12746 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryGetArray<T>(ReadOnlyMemory<T> readOnlyMemory, out ArraySegment<T> arraySegment);

segment

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12754 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryGetArray<T>(ReadOnlySequence<T> sequence, out ArraySegment<T> arraySegment);

segment

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12760 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryGetOwnedMemory<T, TOwner>(ReadOnlyMemory<T> readOnlyMemory, out TOwner ownedMemory) where TOwner : OwnedMemory<T>;

owner

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12755 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryGetOwnedMemory<T, TOwner>(ReadOnlyMemory<T> readOnlyMemory, out TOwner ownedMemory, out int index, out int length) where TOwner : OwnedMemory<T>;

owner

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12756 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryGetOwnedMemory<T, TOwner>(ReadOnlyMemory<T> readOnlyMemory, out TOwner ownedMemory, out int index, out int length) where TOwner : OwnedMemory<T>;

memory

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12756 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static bool TryGetString(ReadOnlyMemory<char> readOnlyMemory, out string text, out int start, out int length);

memory

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12757 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +namespace System.Runtime.Intrinsics {

They are pulled from .NET Core 2.1. Disregard.

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:12766 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by terrajobst** [comment]
> +        public static void ZeroMemory(Span<byte> buffer);

destination

---
Refers to: 2018/NetCore20-vs-NetCore21-Diff/NetCore20-vs-NetCore21-Diff.md:15438 in db85d55. [](commit_id = db85d5555f684607d319a2114bfbda7c7ceae883, deletion_comment = False)

**Comment by stephentoub** [comment]
> Looks like plumbing. Should be in sub namespace.

@terrajobst, can you elaborate?  These are essentially just `Action<..>`, but because span can't be used as a generic type parameter, we had to create custom delegates where we needed delegates that take span, e.g. `String.Create`.

If that's all understood and the agreement was still that they should be in a subnamespace, what namespace?

**Comment by ahsonkhan** [comment]
```text
+    public static class CryptographicOperations {
+        public static bool FixedTimeEquals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right);
+        public static void ZeroMemory(Span<byte> buffer);
+    }
```
This is a new type. The parameter names should be `span`/`other` instead of `left`/`right` and `span` instead of `buffer`.

**Comment by terrajobst** [comment]
Superseded by #63

**Pull request closed without merging**
